- hosts: target
  roles:
    - role: system_setup    # create account, file hierarchy, etc.
      tags: sys, system
    - role: packages        # install required base packages
      tags: pkgs, packages
    - role: cli_facilities  # aliases, bin symbolic links, etc.
      tags: cli, facilities
    - role: i3              # install i3 WM and configure system to use it
      tags: i3
    - role: repositories
      tags: repos, repositories
