- name: Create bash_aliases file in home directory
  template:
    src: bash_aliases.j2
    dest: "{{ account.home }}/.bash_aliases"

- name: Push facilities scripts
  copy:
    src: files/
    dest: "{{ tree.cli }}"
    owner: "{{ account.username }}"
    group: "{{ account.username }}"
    mode: "0744"

- name: Create symlinks to facilities for all .sh scripts in 'files' directory
  file:
      src: "{{ tree.cli }}/{{ item | basename }}"
      path: "/usr/bin/{{ item | basename | splitext | first }}"
      state: link
      force: yes
  with_fileglob: files/*.sh

- name: Bash configuration
  blockinfile:
    path: "{{ account.home }}/.bashrc"
    block: "{{ lookup('template', 'add_to_bashrc') }}"

- name: Git configuration
  community.general.git_config:
    name: "{{ item.name }}"
    scope: "{{ item.scope | default('global') }}"
    value: "{{ item.value }}"
  with_items: "{{ git_config }}"
