- name: Try to work with package manager
  block:
    - name: Expected NTP already installed but try it as a dummy test
      package:
        name: ntp
        state: latest
      ignore_errors: "{{ ansible_check_mode }}"
  rescue:
    - name: Restart NTP because it is likely what prevents working with the package manager
      service:
        name: ntp
        state: restarted
      ignore_errors: true
    - name: Wait a bit that date is updated
      pause:
        seconds: 10

- name: Remove undesired packages
  package:
    name: "{{ pkgs_toremove }}"
    state: absent
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install minimal packages
  tags: pkgs_minimal
  package:
    name: "{{ pkgs_minimal }}"
    state: latest
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install common packages
  tags: pkgs_common
  package:
    name: "{{ pkgs_common }}"
    state: latest
  when: install_lvl.common
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install security related packages
  tags: pkgs_security
  package:
    name: "{{ pkgs_security }}"
    state: latest
  when: install_lvl.security
  ignore_errors: "{{ ansible_check_mode }}"

- name: Snap related stuff
  block:
    - name: Install snapd from repository first
      package:
        name: snapd
        state: latest
    - name: Install snap core packages
      tags: pkgs_snap
      community.general.snap:
         name: "core"
    - name: Install snap packages
      tags: pkgs_snap
      community.general.snap:
         name: "{{ snaps }}"
    - name: Install snap classic packages
      tags: pkgs_snap
      community.general.snap:
         name: "{{ item }}"
         classic: yes
      with_items: "{{ snaps_classic }}"
  when: install_lvl.snap
  tags: pkgs_snap
  ignore_errors: "{{ ansible_check_mode }}"
