git_config:
  - name: core.editor
    value: vim
  - name: diff.tool
    value: vimdiff
  - name: alias.df
    value: difftool
  - name: alias.st
    value: status -sb
  - name: alias.ll
    value: log --oneline
  - name: alias.last
    value: log -1 HEAD --stat
  - name: alias.search
    value: '!git rev-list --all | xargs git grep -F'
  - name: alias.graph
    value: "log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
  - name: alias.graph2
    value: "log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"


