- name: Restart NTP before all as it will take some time to apply
  service:
    name: ntp
    state: restarted
  ignore_errors: true
  tags: always

- block:
    - name: Create group for user
      group:
        name: "{{ account.username }}"
        state: present

    - name: Create user if not present and add it to sudoers
      user:
        name: "{{ account.username }}"
        password: "{{ account.userpass }}"
        home: "{{ account.home }}"
        group: "{{ account.username }}"
        groups:
            - sudo
        append: yes
        generate_ssh_key: yes
        shell: /bin/bash
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ account.username }}"
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_ed25519.pub
        - ~/.ssh/id_rsa.pub
      ignore_errors: True
  tags: user-mgmt


- name: Create filesystem skeleton
  file:
    path: "{{ account.home }}/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_community.general.filetree: filesystem_skeleton/
  when: item.state == 'directory'
